PROJECT = dockerapp
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0



DEPS = \
	  cowboy \
	  recon \
	  gproc

dep_cowboy_commit = 2.4.0
dep_recon = hex 2.3.6
dep_gproc = hex 0.8.0

SHELL_OPTS = \
	-s $(PROJECT) \
    -sname dev

include erlang.mk
