PROJECT = dp_beam
PROJECT_DESCRIPTION = Play with Beam
PROJECT_VERSION = 0.1.0
ERLC_OPTS = +debug_info
LOCAL_DEPS =  crypto observer wx debugger
DEPS = recon
DIALYZER_OPTS = -Wunderspecs -Woverspecs

SHELL_OPTS = \
	-s $(PROJECT)

include erlang.mk
